title: Rybki.party
description: Kanał dla prawdziwych wędkarzy
baseurl: ""
url: "https://rybki.party"
theme: minima

collections:
  authors:
    output: true
  category:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs
  
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      sidebar: left
  # _authors
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  # _category
  - scope:
      path: ""
      type: category
    values:
      layout: category

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter
  - jekyll-gist
  - jekyll-avatar
  - jekyll-sitemap